# Calliope || rust-toolchain.toml
# --------------------------------
# Rust toolchain file.
#
# Authors: @MaxineToTheStars <https://github.com/MaxineToTheStars>
# ----------------------------------------------------------------

[toolchain]
channel = "esp"
