# Calliope || config.toml
# --------------------------------
# Cargo configuration file.
#
# Authors: @MaxineToTheStars <https://github.com/MaxineToTheStars>
# ----------------------------------------------------------------

# Run
[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"

# Environment Information
[env]
ESP_LOGLEVEL = "INFO"

# Build Information
[build]
target = "xtensa-esp32s2-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

# Rust Unstable
[unstable]
build-std = ["core"]
